# -*- coding: utf-8 -*-
"""main .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOU1Rg8e8rVqluSVPl8XIs5OHpdPaWyf
"""

import pandas as pd
import matplotlib.pyplot as plt

# Read CSV file
df = pd.read_csv("sales_data.csv")

# Total sales by product
product_sales = df.groupby("Product")["Sales"].sum()
print("Total sales by product:")
print(product_sales)
print()

# Total sales by month
monthly_sales = df.groupby("Month")["Sales"].sum()
print("Total sales by month:")
print(monthly_sales)
print()

# Plot monthly sales
monthly_sales.plot(marker="o")
plt.title("Monthly Total Sales")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("monthly_sales.png")
plt.show()

# Plot product sales
product_sales.plot(kind="bar")
plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Sales")
plt.tight_layout()
plt.savefig("product_sales.png")
plt.show()